version: "3.8"

services:
  mc:
    image: itzg/minecraft-server:latest
    container_name: mc
    tty: true
    stdin_open: true
    expose:
      - "25565"
    environment:
      EULA: "TRUE"
      MEMORY: "8072M"
      DIFFICULTY: "3"
      LEVEL: "universe"
      SIMULATION_DISTANCE: "12"
      VIEW_DISTANCE: "12"
      PAUSE_WHEN_EMPTY_SECONDS: "3600"
      WHITELIST: |
        Maddi_97
      OPS: |
        Maddi_97  
    volumes:
      - "./data:/data"
    restart: always
    networks:
      - proxy

  nginx-mc:
    image: nginx:latest
    container_name: nginx-minecraft-proxy
    ports:
      - "25565:25565" # Only Nginx binds this port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - mc
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    driver: bridge

